Noticed missing header when was building llvm with gcc-11:
llvm-project/llvm/utils/benchmark/src/benchmark_register.h:17:30:
  error: 'numeric_limits' is not a member of 'std'
   17 |   static const T kmax = std::numeric_limits<T>::max();
      |                              ^~~~~~~~~~~~~~
Signed-off-by: Sergei Trofimovich <slyfox@inbox.ru>

cherry-picked from https://reviews.llvm.org/D89450